### ISSUE TITLE
Multiple tests fail in CLI test

### ISSUE THREAD

**Issue by djwf** [djwf/mail-deduplicate#2]
```
================================================== test session starts ==================================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/dave/usr/src/maildir-deduplicate.git, inifile: setup.cfg
plugins: cov-2.8.1
collected 20 items                                                                                                      

maildir_deduplicate/tests/test_cli.py ..F.F..                                                                     [ 35%]
maildir_deduplicate/tests/test_deduplicate.py .............                                                       [100%]

======================================================= FAILURES ========================================================
____________________________________ TestDeduplicateCLI.test_invalid_maildir_as_file ____________________________________

self = <maildir_deduplicate.tests.test_cli.TestDeduplicateCLI testMethod=test_invalid_maildir_as_file>

    def test_invalid_maildir_as_file(self):
        result = self.invoke('deduplicate', './__init__.py')
        self.assertEqual(result.exit_code, 2)
>       self.assertIn(
            """Directory "./__init__.py" does not exist""", result.output)
E       AssertionError: 'Directory "./__init__.py" does not exist' not found in "Usage: cli deduplicate [OPTIONS] [MAILDIRS]...\nTry 'cli deduplicate --help' for help.\n\nError: Invalid value for '[MAILDIRS]...': Directory './__init__.py' does not exist.\n"

maildir_deduplicate/tests/test_cli.py:54: AssertionError
------------------------------------------------- Captured stdout call --------------------------------------------------
$ mdedupe deduplicate ./__init__.py
Usage: cli deduplicate [OPTIONS] [MAILDIRS]...
Try 'cli deduplicate --help' for help.

Error: Invalid value for '[MAILDIRS]...': Directory './__init__.py' does not exist.

<Result SystemExit(2)>
Traceback (most recent call last):
  File "/home/dave/usr/local/miniconda3/envs/maildir-dedupe/lib/python3.8/site-packages/click/testing.py", line 329, in invoke
    cli.main(args=args or (), prog_name=prog_name, **extra)
  File "/home/dave/usr/local/miniconda3/envs/maildir-dedupe/lib/python3.8/site-packages/click/core.py", line 800, in main
    sys.exit(e.exit_code)
SystemExit: 2
_____________________________________ TestDeduplicateCLI.test_nonexistent_directory _____________________________________

self = <maildir_deduplicate.tests.test_cli.TestDeduplicateCLI testMethod=test_nonexistent_directory>

    def test_nonexistent_directory(self):
        result = self.invoke('deduplicate', './dummy_maildir/')
        self.assertEqual(result.exit_code, 2)
>       self.assertIn(
            """Directory "./dummy_maildir/" does not exist""", result.output)
E       AssertionError: 'Directory "./dummy_maildir/" does not exist' not found in "Usage: cli deduplicate [OPTIONS] [MAILDIRS]...\nTry 'cli deduplicate --help' for help.\n\nError: Invalid value for '[MAILDIRS]...': Directory './dummy_maildir/' does not exist.\n"

maildir_deduplicate/tests/test_cli.py:48: AssertionError
------------------------------------------------- Captured stdout call --------------------------------------------------
$ mdedupe deduplicate ./dummy_maildir/
Usage: cli deduplicate [OPTIONS] [MAILDIRS]...
Try 'cli deduplicate --help' for help.

Error: Invalid value for '[MAILDIRS]...': Directory './dummy_maildir/' does not exist.

<Result SystemExit(2)>
Traceback (most recent call last):
  File "/home/dave/usr/local/miniconda3/envs/maildir-dedupe/lib/python3.8/site-packages/click/testing.py", line 329, in invoke
    cli.main(args=args or (), prog_name=prog_name, **extra)
  File "/home/dave/usr/local/miniconda3/envs/maildir-dedupe/lib/python3.8/site-packages/click/core.py", line 800, in main
    sys.exit(e.exit_code)
SystemExit: 2
=================================================== warnings summary ====================================================
maildir_deduplicate/tests/test_cli.py::TestHashCLI::test_stdin_hashing
  /home/dave/usr/src/maildir-deduplicate.git/maildir_deduplicate/mail.py:221: DeprecationWarning: Flags not at the start of the expression '([Rr]e: )*(\\[\\w[\\w_-' (truncated)
    matching = re.match(

-- Docs: https://docs.pytest.org/en/latest/warnings.html

----------- coverage: platform linux, python 3.8.2-final-0 -----------
Name                                 Stmts   Miss Branch BrPart     Cover
-------------------------------------------------------------------------
maildir_deduplicate/__init__.py         43      2      6      2    91.84%
maildir_deduplicate/cli.py              79     12     22      5    83.17%
maildir_deduplicate/deduplicate.py     253     59     98     19    72.65%
maildir_deduplicate/mail.py            126     39     56     13    65.93%
-------------------------------------------------------------------------
TOTAL                                  501    112    182     39    73.79%

================================================ short test summary info ================================================
FAILED maildir_deduplicate/tests/test_cli.py::TestDeduplicateCLI::test_invalid_maildir_as_file - AssertionError: 'Dire...
FAILED maildir_deduplicate/tests/test_cli.py::TestDeduplicateCLI::test_nonexistent_directory - AssertionError: 'Direct...
======================================== 2 failed, 18 passed, 1 warning in 0.49s ========================================
```

**Comment by djwf** [comment]
Fixed by commit 5746a3a
